/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.*;
import java.awt.event.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author nalux
 */
public class VentanaCargas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCargas
     */
    public VentanaCargas() {
        initComponents();
        generateButtons();
    }
    public VentanaCargas(Sistema unSistema) {
        try {
            this.sistema = unSistema;
        
        this.funcionarios = this.sistema.getFuncionarios();
        this.articulos = this.sistema.getArticulos();
        } catch (NullPointerException e) {
            this.sistema = new Sistema();
             this.funcionarios = this.sistema.getFuncionarios();
        this.articulos = this.sistema.getArticulos();
        }
        
        
        initComponents();
        generateButtons();
     //   contador.setVisible(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCargas().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        onp_aviso = new javax.swing.JOptionPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelIngresoEgreso = new javax.swing.JPanel();
        jLabelIngEgr = new javax.swing.JLabel();
        jLabelFun = new javax.swing.JLabel();
        jLabelArt = new javax.swing.JLabel();
        codigo1E = new javax.swing.JLabel();
        codigo2E = new javax.swing.JLabel();
        art1E = new javax.swing.JLabel();
        art2E = new javax.swing.JLabel();
        cant1E = new javax.swing.JLabel();
        cant2E = new javax.swing.JLabel();
        fun1E = new javax.swing.JLabel();
        fun2E = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        //DefaultListModel<String> model = new DefaultListModel<>();
        listaFun = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        //DefaultListModel<String> model2 = new DefaultListModel<>();
        listaArt = new javax.swing.JList<>();
        jLabelCant = new javax.swing.JLabel();
        jTextFieldCant = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jButtonIngr = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        panelEspacios = new javax.swing.JPanel();
      //  contador = new javax.swing.JLabel();
        contador2 = 0;
        letraArea = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        listaFun.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaFun);

        listaArt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaArt);

        jScrollPane2.setVisible(false);
        jScrollPane1.setVisible(false);
        jTextFieldCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantActionPerformed(evt);
            }
        });

        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jButtonIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIngresoEgresoLayout = new javax.swing.GroupLayout(PanelIngresoEgreso);
        PanelIngresoEgreso.setLayout(PanelIngresoEgresoLayout);
        PanelIngresoEgresoLayout.setHorizontalGroup(
            PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jLabelFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresoEgresoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCant, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresoEgresoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIngr)
                .addGap(20, 20, 20))
            .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelIngEgr, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelIngresoEgresoLayout.setVerticalGroup(
            PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelIngEgr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                        .addComponent(jLabelCant, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(PanelIngresoEgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIngresoEgresoLayout.createSequentialGroup()
                        .addComponent(jTextFieldCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIngr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelIngresoEgreso);
        PanelIngresoEgreso.setBounds(710, 90, 370, 300);

        panelEspacios.setLayout(new java.awt.GridLayout(12, 10));
        getContentPane().add(panelEspacios);
        panelEspacios.setBounds(30, 60, 610, 460);
      
        panelEspacios.setBackground(Color.YELLOW);

     //   contador.setText("0");
//        getContentPane().add(contador);
//        contador.setBounds(440, 560, 37, 16);

        letraArea.setText("A");
        getContentPane().add(letraArea);
        letraArea.setBounds(170, 0, 60, 16);

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 540, 72, 22);

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 540, 72, 22);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1165, 635));
        setLocationRelativeTo(null);

        jButtonIngr.setVisible(false);
        jTextFieldCod.setVisible(false);
        jTextFieldCant.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
        jTextFieldCod.getText();
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    

    /** Asumiendo que los datos cantArticulos y codigoCargas son correctos, y que
     * el usuario seleccionó un funcionario y un articulo de las listas correspondientes,
     * crea una carga con esos datos y la agrega a la lista.
     * @param cantArticulos cantidad de articulos que hay en la carga
     * @param codigoCarga código identificador de la carga*/
    private void agregarCargaManual(int cantArticulos, String codigoCarga) {
        String nombreFuncionario = listaFun.getSelectedValue();
        String nombreArticulo = listaArt.getSelectedValue();

        Funcionario func = sistema.buscarFuncionarioPorNombre(nombreFuncionario);
        Articulo art = sistema.buscarArticuloPorNombre(nombreArticulo);

        Carga nueva = new Carga(func, art, cantArticulos, codigoCarga);

        sistema.agregarCarga(contador2, filaSeleccionada, colSeleccionada, nueva);
    }

    /** Si los datos que el usuario ingresó (funcionario y articulo seleccionado, y cantidad y codigo de carga)
     * son validos y no nulos, entonces llama a agregarCargaManual. De lo contrario, informa al usuario
     * para que vuelva a ingresar o seleccionar los datos de manera correcta.*/
    private void agregarSegunDatos() {
        if(listaFun.getSelectedValue() == null || listaArt.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(onp_aviso,
                "Debe seleccionar tanto un usuario como un artículo.", "Datos incompletos",
                + JOptionPane.ERROR_MESSAGE);

        } else {
            try {
                String codigoCarga = jTextFieldCod.getText();
                String cantArt = jTextFieldCant.getText();
                
                if (!codigoCarga.equals("") && !cantArt.isEmpty()) {
                    int cantArticulos = Integer.parseInt(cantArt);

                    if (cantArticulos > 0) {
                        agregarCargaManual(cantArticulos, codigoCarga);
                        JOptionPane.showMessageDialog(onp_aviso,
                            "La carga fue ingresada correctamente.", "Carga ingresada",
                            + JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(onp_aviso,
                        "La cantidad debe ser mayor a cero", "Datos incorrectos",
                        + JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(onp_aviso,
                        "Debe ingresar una cantidad y un codigo de carga", "Datos incompletos",
                        + JOptionPane.ERROR_MESSAGE);
                }
            
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(onp_aviso,
                "La cantidad debe ser un número entero", "Datos incorrectos",
                + JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void jButtonIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngrActionPerformed
        // TODO add your handling code here:
        if (jButtonIngr.getText().equals("Ingresar")) {
            agregarSegunDatos();
        } else {
            //cosas de egreso
        }
    }

    private void jTextFieldCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantActionPerformed
        // TODO add your handling code here:
        jTextFieldCant.getText();
    }//GEN-LAST:event_jTextFieldCantActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       if (contador2 == 0) {
           letraArea.setText("E");
            contador2 = 4;
            System.out.println("Deberia valer 4, y vale " + contador2);
        } else {
           System.out.print("Deberia valer " + (contador2-1) + ", y vale ");
           contador2--;
           System.out.println(contador2);
           letraArea.setText(sistema.areas[contador2]);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (contador2 == 4) {
            contador2 = 0;
            letraArea.setText("A");
            System.out.println("Deberia valer 0, y vale " + contador2);
        } else {
            System.out.print("Deberia valer " + (contador2+1) + ", y vale ");
            contador2++;
            System.out.println(contador2);
            letraArea.setText(sistema.areas[contador2]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void generateButtons() {
        for (int i = 0; i < 12; i++) {
            for (int j = 0; j < 10; j++) {
                JButton nuevo = new JButton(" ");
                nuevo.setMargin(new Insets(-5, -5, -5, -5));
                nuevo.setBackground(Color.GRAY);
                nuevo.setForeground(Color.WHITE);
                String aux1 = i + 1 + ".";
                int aux2 = j + 1;
                
                nuevo.setText(aux1 + aux2);
                nuevo.setBorder(new RoundedBorder(10));
                nuevo.addActionListener(new VentanaCargas.EspacioListener());
                this.panelEspacios.add(nuevo);
            }
        }
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIngresoEgreso;
    //private javax.swing.JLabel contador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonIngr;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelCant;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelFun;
    private javax.swing.JLabel jLabelIngEgr;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCant;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JLabel letraArea;
    private javax.swing.JList<String> listaArt;
    private javax.swing.JList<String> listaFun;
    private javax.swing.JPanel panelEspacios;
    // End of variables declaration//GEN-END:variables
    private Sistema sistema;
    private ArrayList<Funcionario> funcionarios;
    private ArrayList<Articulo> articulos;
    private int contador2;
    private int filaSeleccionada;
    private int colSeleccionada;
    private javax.swing.JOptionPane onp_aviso;
    private JButton botonAnterior;
    private class EspacioListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
// este código se ejecutará al presionar el botón, obtengo cuál botón
            
            JButton cual = ((JButton) e.getSource());
            cual.setBackground(Color.red);
            botonAnterior.setBackground(Color.GRAY);
            String pos = cual.getText();
            String[] parts = pos.split("\\.");
            int part1 = Integer.parseInt(parts[0]); 
            int part2 = Integer.parseInt(parts[1]); 
            filaSeleccionada = part1-1;
            colSeleccionada = part2-1;
            if(sistema.getCargas().get(contador2)[part1-1][part2-1] == null){
                ingreso();
                PanelIngresoEgreso.setBackground(Color.GREEN);
            }
            else {
                egreso();
                PanelIngresoEgreso.setBackground(Color.BLUE);
                
               // cargaListaFuncionarios();
                //cargarListaArticulos();
                // int cant = Integer.parseInt(jTextFieldCant.getText());
                 // int cod = Integer.parseInt(jTextFieldCod.getText());
                
                
            }
          
            jScrollPane2.setVisible(true);
            jScrollPane1.setVisible(true);
            jButtonIngr.setVisible(true);
            jTextFieldCod.setVisible(true);
            jTextFieldCant.setVisible(true);

            botonAnterior = cual;
            
            // código a completar según el botón presionado
            //hago funcion de ingreso con set visible y la llamo cuando corresponda
//hago metodo que haga visible cuando ingrese
//hago otro metodo que se haga visible cuando egrese
            // public void ingreso() {

            //  if()
            //sni la lista de cargas en esa posicion es null
            //ingreso
            // relacion entre boton y lugar de sstema
            //tengo array de matrices a b c d e 
            //
            //dominio.sistema.cargas[i]
            //dominio.sistema.cargas.get(i) eso devuelve objeto de tipo matriz
          // sistema.cargas es un arraylist por eso uso get
          //contador me ice en que area estoy 
          //obtengo en que area: sistema.cargas.get(Integer.parseInt(contador.getText()))
          // estoy en una matriz, como obtengo i y j? depende del boton
          //relacion matriz boton?
          //cual ya tiene sus numeros literal es como i y j 
          //String pos = cual.getText();
          //String[] parts = string.split(".");
            //String part1 = Integer.parseInt(parts[0]); 
            //String part2 = Integer.parseInt(parts[1]); 
            //sistema.cargas.get(Integer.parseInt(contador.getText())) [part1] [part2];
          
        }
//
        }
    //hago metodo para el panel de ingreso
    public void ingreso(){
        mostrarPanelIngreso(true);
        jLabelIngEgr.setText("Ingreso");
        jLabelFun.setText("Funcionarios");
        jLabelArt.setText("Articulos");
        jLabelCant.setText("Cantidad");
        jLabelCodigo.setText("Codigo");
        jButtonIngr.setText("Ingresar");
        
        String f[] = new  String [sistema.getFuncionarios().size()];
        for(int i=0; i<f.length; i++ ){
            f[i]= sistema.getFuncionarios().get(i).getNombre();
        } 
        
        listaFun.setListData(f);
        
        String a[] = new  String [sistema.getArticulos().size()];
        for(int i=0; i<a.length; i++ ){
            a[i]= sistema.getArticulos().get(i).getNombre();
        } 
        listaArt.setListData(a);
    }

    public void mostrarPanelIngreso(boolean mostrar) {
        jLabelArt.setVisible(!mostrar);
        jLabelCant.setVisible(!mostrar);
        jLabelCodigo.setVisible(!mostrar);
        jLabelFun.setVisible(!mostrar);
  
        listaArt.setVisible(mostrar);
        listaFun.setVisible(mostrar);
        jButtonIngr.setVisible(mostrar);
        jScrollPane1.setVisible(mostrar);
        jScrollPane2.setVisible(mostrar);
        jTextFieldCant.setVisible(mostrar);
        jTextFieldCod.setVisible(mostrar);
    }

    private JLabel codigo1E;
    private JLabel codigo2E;
    private JLabel art1E;
    private JLabel art2E;
    private JLabel cant1E;
    private JLabel cant2E;
    private JLabel fun1E;
    private JLabel fun2E;

    public void egreso(){
      Carga cargaActual = sistema.getCargas().get(contador2)[filaSeleccionada][colSeleccionada];
      jLabelIngEgr.setText("Egreso");
      art2E.setText(cargaActual.getArticulo().getNombre());
      cant2E.setText(String.valueOf(cargaActual.getCantUnidades()));
      codigo2E.setText(cargaActual.getCodigo());
      fun2E.setText(cargaActual.getFuncionario().getNombre());


      mostrarPanelIngreso(false);
      
    }
  
    }
  
    
    class RoundedBorder implements Border {
        
        private int radius;
    
    
        RoundedBorder(int radius) {
            this.radius = radius;
        }
    
    
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }
    
    
        public boolean isBorderOpaque() {
            return true;
        }
    
    
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width-1, height-1, radius, radius);
        }
        
    }