/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Dominio.Dron;
import Dominio.Sistema;
import Dominio.Vuelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ylian
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
    }

    public Estadisticas(Sistema datos) {
        this.datos = datos;
        
        initComponents();
        
        cargarListasDrones();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onp_aviso = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_datosVuelo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_conVuelos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_sinVuelos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_ver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadísticas");

        jScrollPane1.setViewportView(lst_datosVuelo);
        lst_datosVuelo.setVisible(true);
        jScrollPane2.setVisible(true);

        lst_conVuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_conVuelos.setToolTipText("");
        jScrollPane2.setViewportView(lst_conVuelos);

        lst_sinVuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_sinVuelos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_sinVuelosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lst_sinVuelos);

        jLabel1.setText("Vuelos del dron");
        jLabel1.setVisible(true);

        jLabel2.setText("Drones sin vuelos");

        jLabel3.setText("Drones con vuelos");

        btn_ver.setText("Ver vuelos");
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_ver)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addGap(31, 31, 31)
                .addComponent(btn_ver)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        // TODO add your handling code here:
        if (lst_sinVuelos.getSelectedValue().isEmpty() || lst_conVuelos.getSelectedValue().isEmpty()) {
            JOptionPane.showMessageDialog(onp_aviso, "Por favor, elija un dron de"
                   + " la lista de drones con vuelos.", 
                 "No hay vuelos",JOptionPane.ERROR_MESSAGE);
        } else {
            Dron dronSeleccionado = datos.buscarDronPorID(lst_conVuelos.getSelectedValue());
            cargarListaVuelo(dronSeleccionado);
        } 
    }//GEN-LAST:event_btn_verActionPerformed

    private void lst_sinVuelosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_sinVuelosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lst_sinVuelosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }
    
    private String datosVuelo(Vuelo unVuelo) {
        String datosVuelo = new String();
        datosVuelo = "Archivo: " + unVuelo.getArchivo() + "\n"
                + "Area: "+ unVuelo.getArea() + "\n"
                + "Fila: "+ unVuelo.getFila() + "\n";
        
        if (unVuelo.getCargas().length == 10) {
            datosVuelo += "Coincidencias: " + String.valueOf(unVuelo.getCoincidencias()) + "\n"
                    + "Diferencias: " + String.valueOf(unVuelo.getDiferencias()) + "\n";
        } else {
            datosVuelo += "Lineas de carga: " + unVuelo.getCargas().length;
        }
        
        return datosVuelo;    
    }
    
    private void cargarListaVuelo(Dron unDron) {
        ArrayList<Vuelo> vuelosDron = datos.vuelosDeUnDron(unDron);
        
        String[] info = new String[vuelosDron.size()];
        for (int i = 0; i < info.length; i++) {
            info[i] = datosVuelo(vuelosDron.get(i));
        }
        
        lst_datosVuelo.setListData(info);
    }
    
    
    
    private void cargarListasDrones() {
      ArrayList<Dron> dronesConVuelos = datos.dronesConVuelos();
      ArrayList<Dron> dronesSinVuelos = datos.dronesSinVuelos();  
              
      String conVuelos[] = new  String [dronesConVuelos.size()];
      String sinVuelos[] = new  String [dronesSinVuelos.size()];
      
      for (int pos = 0; pos < conVuelos.length; pos++) {
          conVuelos[pos] = dronesConVuelos.get(pos).getIdentificacion();
      }
      
      for (int pos = 0; pos < sinVuelos.length; pos++) {
          sinVuelos[pos] = dronesSinVuelos.get(pos).getIdentificacion();
      }
      
      lst_conVuelos.setListData(conVuelos);
      lst_sinVuelos.setListData(sinVuelos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst_conVuelos;
    private javax.swing.JList<String> lst_datosVuelo;
    private javax.swing.JList<String> lst_sinVuelos;
    private javax.swing.JOptionPane onp_aviso;
    // End of variables declaration//GEN-END:variables
    private Sistema datos;
    
    
}
