package Interfaz;

import Dominio.Dron;
import Dominio.Sistema;
import Dominio.Vuelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/** Ventana de Estadísticas.
 * @author yliana*/
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
    }

    public Estadisticas(Sistema datos) {
        this.datos = datos;
        
        initComponents();
        
        cargarListasDrones();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onp_aviso = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_vuelosDelDron = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_dronesConVuelos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_dronesSinVuelos = new javax.swing.JList<>();
        lbl_vuelosDelDron = new javax.swing.JLabel();
        lbl_dronesSinVuelos = new javax.swing.JLabel();
        lbl_dronesConVuelos = new javax.swing.JLabel();
        btn_verVuelos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadísticas");
        setBounds(new java.awt.Rectangle(500, 400, 828, 400));

        lst_vuelosDelDron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lst_vuelosDelDron.setEnabled(false);
        jScrollPane1.setViewportView(lst_vuelosDelDron);
        lst_vuelosDelDron.setVisible(true);
        jScrollPane2.setVisible(true);

        lst_dronesConVuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lst_dronesConVuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_dronesConVuelos.setToolTipText("");
        jScrollPane2.setViewportView(lst_dronesConVuelos);

        lst_dronesSinVuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lst_dronesSinVuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_dronesSinVuelos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_dronesSinVuelosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lst_dronesSinVuelos);

        lbl_vuelosDelDron.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_vuelosDelDron.setText("Vuelos del dron");
        lbl_vuelosDelDron.setVisible(true);

        lbl_dronesSinVuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_dronesSinVuelos.setText("Drones sin vuelos");

        lbl_dronesConVuelos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_dronesConVuelos.setText("Drones con vuelos");

        btn_verVuelos.setText("Ver vuelos");
        btn_verVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verVuelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_dronesSinVuelos)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dronesConVuelos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btn_verVuelos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_vuelosDelDron))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vuelosDelDron)
                    .addComponent(lbl_dronesConVuelos)
                    .addComponent(lbl_dronesSinVuelos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1))
                .addGap(31, 31, 31)
                .addComponent(btn_verVuelos)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verVuelosActionPerformed
        // TODO add your handling code here:
        if (lst_dronesConVuelos.isSelectionEmpty() || !lst_dronesSinVuelos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(onp_aviso, "Por favor, elija un dron de"
                   + " la lista de drones con vuelos.", 
                 "No hay vuelos",JOptionPane.ERROR_MESSAGE);
        } else {
            Dron dronSeleccionado = datos.buscarDronPorID(lst_dronesConVuelos.getSelectedValue());
            cargarListaVuelo(dronSeleccionado);
        } 
    }//GEN-LAST:event_btn_verVuelosActionPerformed

    private void lst_dronesSinVuelosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_dronesSinVuelosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lst_dronesSinVuelosValueChanged

    
    private String datosVuelo(Vuelo unVuelo) {
        String datosVuelo = new String();
        datosVuelo = "Archivo: " + unVuelo.getArchivo() + " \n "
                + "Area: "+ unVuelo.getArea() + " \n "
                + "Fila: "+ unVuelo.getFila() + " \n ";
        
        if (unVuelo.getCargas().length == 10) {
            datosVuelo += " Coincidencias: " + String.valueOf(unVuelo.getCoincidencias()) + " \n "
                    + " Diferencias: " + String.valueOf(unVuelo.getDiferencias()) + " \n  ";
        } else {
            datosVuelo += "Lineas de carga: " + unVuelo.getCargas().length +" ";
        }
        
        
        return datosVuelo;    
    }
    
    private void cargarListaVuelo(Dron unDron) {
        ArrayList<Vuelo> vuelosDron = datos.vuelosDeUnDron(unDron);
        
        String[] info = new String[vuelosDron.size()];
        for (int i = 0; i < info.length; i++) {
            info[i] = datosVuelo(vuelosDron.get(i));
        }
        
        lst_vuelosDelDron.setListData(info);
    }
    
    private void cargarListasDrones() {
      ArrayList<Dron> dronesConVuelos = datos.dronesConVuelos();
      ArrayList<Dron> dronesSinVuelos = datos.dronesSinVuelos();  
              
      String conVuelos[] = new  String [dronesConVuelos.size()];
      String sinVuelos[] = new  String [dronesSinVuelos.size()];
      
      for (int pos = 0; pos < conVuelos.length; pos++) {
          conVuelos[pos] = dronesConVuelos.get(pos).getIdentificacion();
      }
      
      for (int pos = 0; pos < sinVuelos.length; pos++) {
          sinVuelos[pos] = dronesSinVuelos.get(pos).getIdentificacion();
      }
      
      lst_dronesConVuelos.setListData(conVuelos);
      lst_dronesSinVuelos.setListData(sinVuelos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_verVuelos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_dronesConVuelos;
    private javax.swing.JLabel lbl_dronesSinVuelos;
    private javax.swing.JLabel lbl_vuelosDelDron;
    private javax.swing.JList<String> lst_dronesConVuelos;
    private javax.swing.JList<String> lst_dronesSinVuelos;
    private javax.swing.JList<String> lst_vuelosDelDron;
    private javax.swing.JOptionPane onp_aviso;
    // End of variables declaration//GEN-END:variables
    private Sistema datos;
    
    
}
